version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: lms_0k07
      POSTGRES_USER: lms_0k07_user
      POSTGRES_PASSWORD: NoyxR2mDrrFD5E1JnOYjPDSAFxfirOjG
    ports:
      - "5432:5432"
